// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVXMLajFwa3FWngjRBDqCayVcUz1TSdHg',
    appId: '1:797565047110:web:24be3a239080428b821547',
    messagingSenderId: '797565047110',
    projectId: 'guidly-90eb5',
    authDomain: 'guidly-90eb5.firebaseapp.com',
    storageBucket: 'guidly-90eb5.appspot.com',
    measurementId: 'G-70C5JDCJGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6W27Lsbsg98p-hUF019Uq7LPSriUm9O4',
    appId: '1:797565047110:android:bbae19f97df5dbca821547',
    messagingSenderId: '797565047110',
    projectId: 'guidly-90eb5',
    storageBucket: 'guidly-90eb5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA99of_W8_BdldjVIOnoZ5Xi6978lAxymQ',
    appId: '1:797565047110:ios:d3ce82b4bae6e2fc821547',
    messagingSenderId: '797565047110',
    projectId: 'guidly-90eb5',
    storageBucket: 'guidly-90eb5.appspot.com',
    iosClientId:
        '797565047110-jsrpgkf7ormpmin4mdaj7bcqrpld5stq.apps.googleusercontent.com',
    iosBundleId: 'com.example.guidly',
  );
}
